<script src="//code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
<script>
    var JQry = jQuery.noConflict();
    JQry(function()
    {
        var windowHeight = window.innerHeight;
        JQry('html').css('height', windowHeight + 'px');
        JQry('.middle').css('min-height', '0px');
        var bodyHeight = JQry('body').css('height');
        var res = windowHeight - parseFloat(JQry('.footer').outerHeight()) - parseFloat(JQry('.header').outerHeight()) - 30;
        JQry('#anchor-content').css('height', res + 'px');
        JQry('#anchor-content').children().css('height', '100%');
        JQry('#iframe').css('height', '100%');
        JQry(window).resize(function()
        {
            var windowHeight = window.innerHeight;
            JQry('html').css('height', windowHeight + 'px');
            var res = windowHeight - parseFloat(JQry('.footer').outerHeight()) - parseFloat(JQry('.header').outerHeight()) - 30;
            JQry('#anchor-content').css('height', res + 'px');
        }).resize();
    })
</script>
<?
function url_origin($s, $use_forwarded_host=false)
{
    $ssl = (!empty($s['HTTPS']) && $s['HTTPS'] == 'on') ? true:false;
    $sp = strtolower($s['SERVER_PROTOCOL']);
    $protocol = substr($sp, 0, strpos($sp, '/')) . (($ssl) ? 's' : '');
    $port = $s['SERVER_PORT'];
    $port = ((!$ssl && $port=='80') || ($ssl && $port=='443')) ? '' : ':'.$port;
    $host = ($use_forwarded_host && isset($s['HTTP_X_FORWARDED_HOST'])) ? $s['HTTP_X_FORWARDED_HOST'] : (isset($s['HTTP_HOST']) ? $s['HTTP_HOST'] : null);
    $host = isset($host) ? $host : $s['SERVER_NAME'] . $port;
    return $protocol . '://' . $host;
}
function full_url($s, $use_forwarded_host=false)
{
    return url_origin($s, $use_forwarded_host) . $s['REQUEST_URI'];
}
$absolute_url = full_url($_SERVER);

$charge = Mage::app()->getRequest()->getParam('charge');

if ($charge)
{
    Mage::getModel('core/config')->saveConfig('gshift/payment/id', $charge);
    header('Location: ' . Mage::helper('adminhtml')->getUrl('gshift/adminhtml_gshiftbackend/index'));
    die();
}
else
{
    $charge = Mage::getStoreConfig('gshift/payment/id');
}
?>

<iframe id="iframe" style="width: 100%; height: 100%; border: none" src="https://shopify.webpresenceoptimizer.com/magento/index?site_url=<?=$absolute_url?>&charge=<?= $charge?>">
</iframe>